# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-24 00:15
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0004_auto_20200323_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='caption',
            field=djstripe.fields.StripeCharField(blank=True, default='', help_text='A short one-line description of the product, meant to be displayableto the customer. Only applicable to products of `type=good`.', max_length=5000, null=True),
        ),
    ]
