# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-24 00:16
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0005_auto_20200323_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=djstripe.fields.StripeCharField(default='', help_text='A URL of a publicly-accessible webpage for this product. Only applicable to products of `type=good`.', max_length=799, null=True),
        ),
    ]
